# -*- coding: utf-8 -*-
"""python_zero_to_hero_assignment_1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1oO_GVCwM2OazeInIcBMCRJr5k-OcprQS
"""

x=int(input("please enter your first number"))
y = int(input("please enter your second number"))
print(f"result = {x**y}")

3